### ISSUE TITLE
请问The page has expired due to inactivity. Please refresh and try again. 是为什么

### ISSUE THREAD

**Issue by yiyayamaya** [DavidNineRoc/monday-shop#10]
完全按照教程做的 没报错

**Comment by yiyayamaya** [comment]
.env.example 就只加了数据库的配置

**Comment by yiyayamaya** [comment]
网上搜The page has expired due to inactivity. Please refresh and try again 都说是没加csrf 但是这个项目里不缺csrf

**Comment by DavidNineRoc** [comment]
@yiyayamaya 是否执行了`php artisan moon:install`, 查看 .env 文件的 APP_KEY 是否存在

**Comment by yiyayamaya** [comment]
执行了  APP_KEY 也是在的

**Comment by DavidNineRoc** [comment]
@yiyayamaya 请查看`storage/logs`下最新报错日志文件,并带上截图

**Comment by 951240778** [comment]
> 完全按照教程做的 没报错

部署成功了吗？快乐风男

**Comment by yiyayamaya** [comment]
> > 完全按照教程做的 没报错
> 
> 部署成功了吗？快乐风男

用了homestead成功了 本地不知道为啥不行。。
