### ISSUE TITLE
秒杀缺少方法

### ISSUE THREAD

**Issue by kechujian** [DavidNineRoc/monday-shop#15]
秒杀过程缺少方法
  // 创建一个秒杀主表订单和明细表订单，默认数量一个
            $masterOrder = $this->newMasterOrder($addressId)->setAttribute('type', OrderTypeEnum::SEC_KILL);
            $this->storeSingleOrder($masterOrder, $redisSeckill->product->uuid, 1);

**Comment by DavidNineRoc** [comment]
@kechujian 已修复此问题，thx.  
45acb25da4c8516250873d7d5b85c005ef309d8d
