### ISSUE TITLE
请问，怎么取消推送邮件这项功能呢？

### ISSUE THREAD

**Issue by TheMasterOfMagic** [DavidNineRoc/monday-shop#4]
如果不在`.env`里填好邮件相关的那几个参数的话，就会导致`php artisan gps:install`失败，卡在`Failed:     App\Mail\UserRegister`这里。
想请教一下，怎么才能跳过这一步，取消推送邮件这项功能而不影响其他功能正常运行呢？

**Comment by DavidNineRoc** [comment]
直接取消掉 cmd 命令就行
