### ISSUE TITLE
支付宝支付 微信支付

### ISSUE THREAD

**Issue by uniteweiwei** [DavidNineRoc/monday-shop#6]
支付宝支付
微信支付,在商城里面看见了
![image](https://user-images.githubusercontent.com/19373139/40340228-81698ac4-5db0-11e8-86c6-6ec19bff77ed.png),这个payment配置文件,但是发现商城用的是哪个第三方包.这块是要自己重写吧?

**Comment by DavidNineRoc** [comment]
这是使用的是第三方，因为支付宝和微信不支持个人用户。

**Comment by DavidNineRoc** [comment]
PaysAPI
