### ISSUE TITLE
ERR wrong number of arguments for 'mget' command

### ISSUE THREAD

**Issue by Geek3carl** [DavidNineRoc/monday-shop#8]
"ERR wrong number of arguments for 'mget' command"

**Comment by DavidNineRoc** [comment]
@Geek3carl Please give me your error report

**Comment by DavidNineRoc** [comment]
@JeffcottLu Whether the**redis**service is enabled

**Comment by JeffcottLu** [comment]
> @JeffcottLu Whether the **redis** service is enabled

en, i've sovled this problem;

this accounts to my colleague haven't consecutive the "php artisan moon:install" command, result to no data in redis; 

THX
