### ISSUE TITLE
ERROR: ERR wrong number of arguments for 'mget' command 

### ISSUE THREAD

**Issue by zevgithub** [DavidNineRoc/monday-shop#9]
@DavidNineRoc 
What is the reason for this error? 
Redis is installed and running in the local environment, and access is normal;

 local.ERROR: ERR wrong number of arguments for 'mget' command {"userId":1,"email":"david@qq.com","exception":"[object] (Predis\\Response\\ServerException(code: 0): ERR wrong number of arguments for 'mget' command at /var/www/monday/v-shopendor/predis/predis/src/Client.php:370)

**Comment by DavidNineRoc** [comment]
Try to tell me what you did.

**Comment by DavidNineRoc** [comment]
![image](https://user-images.githubusercontent.com/28035971/51996360-847bcb80-24ef-11e9-8991-5ba293db6e08.png)
I have tried to do it again from the beginning and found no error. I hope you can provide more information to help me fix this problem.

**Comment by zevgithub** [comment]
@DavidNineRoc 

```
//app/Models/Seckill.php
public static function boot()
    {
        parent::boot();
        // 存入 redis
        static::created(function (Seckill $seckill) {
            // 从数据库中取出, 因为有一些默认值
            $seckill = Seckill::query()->find($seckill->id);
            $seckill->load('product');

            // 以后的数据都将从 redis 取出，直至秒杀结束
            \Redis::set($seckill->getRedisModelKey(), $seckill->toJson());**
            // 填充一个 redis 队列，数量为抢购的数量，后面的 9 无意义
            // 当去队列的值时，只需要判断是否为 null，就可以得知还有没有数量
            $fill = array_fill(0, $seckill->number, 9);
            \Redis::lpush($seckill->getRedisQueueKey(), $fill);

            // 秒杀商品，如果用户收藏，发送邮件提醒活动
            RemindUsersHasSeckill::dispatch($seckill);
        });
    }
```

```
//app/Http/Controllers/HomeController.php
$keys = Redis::keys('seckills:*:model');
$secKills = Redis::connection()->mget($keys);
```

```
#dump($categories, $hotProducts,$latestProducts,$users);
Collection {#436 ▼
  #items: array:8 [▼
    0 => Category {#446 ▶}
    1 => Category {#447 ▶}
    2 => Category {#448 ▶}
    3 => Category {#449 ▶}
    4 => Category {#450 ▶}
    5 => Category {#451 ▶}
    6 => Category {#452 ▶}
    7 => Category {#453 ▶}
  ]
}
Collection {#456 ▼
  #items: array:3 [▼
    0 => Product {#457 ▶}
    1 => Product {#458 ▶}
    2 => Product {#459 ▶}
  ]
}
Collection {#467 ▼
  #items: array:9 [▶]
}
Collection {#477 ▼
  #items: array:10 [▼
    0 => User {#478 ▶}
    1 => User {#479 ▶}
    2 => User {#480 ▶}
    3 => User {#481 ▶}
    4 => User {#482 ▶}
    5 => User {#483 ▶}
    6 => User {#484 ▶}
    7 => User {#485 ▶}
    8 => User {#486 ▶}
    9 => User {#487 ▶}
  ]
}
//dd($keys);
[]
```

My redis running environment and testing are normal, the client can also execute commands normally after the connection, the process and port are also normal.
I think the problem should be here，“ \Redis::set”   and “\Redis::lpush ()”
the model did not place data at boot，then causes the key-value pair data to be empty when the page is loaded.

How can I solve it?

**Comment by DavidNineRoc** [comment]
This problem is because I did not judge the empty array when I took redis value. I have fixed this problem. Thank you for your issue
https://github.com/DavidNineRoc/monday-shop/commit/a0b0c7b2e7a7ba5e99bae026d71b82937dc279ca

**Comment by zevgithub** [comment]
Thank you too
